language: python
python:
  - "3.8"  # Use a more recent version of Python

before_install:
  - cd ..
  - wget http://www.renpy.org/dl/6.99.12/renpy-6.99.12-sdk.tar.bz2
  - tar xf renpy-6.99.12-sdk.tar.bz2
  - rm renpy-6.99.12-sdk.tar.bz2
  - cd renpy-6.99.12-sdk

env:
  - SDL_AUDIODRIVER=dummy

script:
  - ./renpy.sh "../swans_self/" lint
